// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function group(arr, make, merge) {
  return arr.reduce((function (acc, v) {
                var last = acc.pop();
                if (last !== undefined) {
                  var merged = Curry._2(merge, last, v);
                  if (merged !== undefined) {
                    acc.push(Caml_option.valFromOption(merged));
                  } else {
                    acc.push(last);
                    acc.push(Curry._1(make, v));
                  }
                } else {
                  acc.push(Curry._1(make, v));
                }
                return acc;
              }), []);
}

var $$Array = {
  group: group
};

exports.$$Array = $$Array;
/* No side effect */
